OptiCorp/TurbinSikker-App

src/BasicStyling/App.css
src/components/Login/index.tsx
src/components/Login/styles.ts

add background color and backdrop-filter to LoginContainer.
add FormWrapper to wrap form and add styling.
adjusted font size and text-shadow of Header and Infotext.

style(Login): styling changes/layout fixes

---

package-lock.json
package.json
src/pages/landingPage/context/LandingPageContextProvider.tsx
src/pages/users/AddUser.tsx
src/pages/users/styles.ts

added uuidv4 dependency, fixed forms for adding user function, new users sends now form data/new user to databse. Add landing page context, work on progress/api context for fetching data/tokens. plus form styling.

feat: :heavy_plus_sign: added uuidv4() to generate user Id's

---

src/App.tsx
src/assets/App.css
src/components/header/Header.tsx
src/pages/landingPage/LandingPage.tsx
src/pages/landingPage/context/LandingPageContextProvider.tsx
src/pages/profile/index.tsx
src/pages/profile/styles.ts
src/pages/users/AddUser.tsx
src/pages/users/context/apiContextProvider.tsx
src/pages/users/listUsers/ListUsers.tsx
src/pages/users/listUsers/styles.ts

…age API data and user creation and listing the users from the database.
refactor(ListUsers.tsx): change list wrapper layout to improve UI and added EDS storybook table to store user list in. feat(ListUsers.tsx): add context to fetch user data from API feat (Header.tsx): add back button and pathlocation name sourced from react router in Header.
+ etc style fixes

 new context provider, `ApiContextProvider`, UserList, Route rendering

---

src/App.tsx
src/components/snackbar/SnackBar.tsx
src/components/snackbar/SnackBarContext.tsx
src/pages/landingPage/context/LandingPageContextProvider.tsx
src/pages/users/Edit/editUserNav.tsx
src/pages/users/addUser/AddUser.tsx
src/pages/users/addUser/addUserNavigation/AddUserNAV.tsx
src/pages/users/addUser/hooks/useAddUser/index.ts
src/pages/users/addUser/inputField/index.tsx
src/pages/users/addUser/roleSelector/index.tsx
src/pages/users/addUser/styles.ts
src/pages/users/addUser/types.ts
src/pages/users/context/apiContextProvider.tsx
src/pages/users/listUsers/ListUsers.tsx
src/pages/users/listUsers/styles.ts
src/pages/users/listUsers/userRow/index.tsx
tsconfig.json
vite.config.ts

new feat: <SnackBar/> and snackbar context to enable users to get notified about users added/edited and deleted.
refactoring: cleaning up in AddUser page, moving files and creating hooks to retrieve data rather than having it all in one page, along with moving types to its own file.
added own index.tsx for user rows for the userlist.tsx
styling changes done to listUsers, and fixes to fetching and retriving data.
added resolvers to vite.config.ts in order to easier import parent files

feat: ✨ added SnackBar for notifications of user handling

---

package-lock.json
package.json
prettierrc.json
src/App.tsx
src/assets/App.css
src/components/navigation/Navigation.tsx
src/models/CheckListEntity.ts
src/models/TaskEntity.ts
src/models/UserEntity.ts
src/pages/checklist/CheckList.tsx
src/pages/checklist/CheckListRowAll.tsx
src/pages/checklist/checkListID/CheckListIDrow.tsx
src/pages/checklist/checkListID/MyCheckLists.tsx
src/pages/checklist/index.tsx
src/pages/checklist/previewCheckList/Preview.tsx
src/pages/checklist/previewCheckList/PreviewList.tsx
src/pages/checklist/previewCheckList/styles.ts
src/pages/checklist/styles.ts
src/pages/context/apiContextProvider.tsx
src/pages/login/styles.ts
src/pages/users/Edit/editUserNav.tsx
src/pages/users/addUser/AddUser.tsx
src/pages/users/addUser/hooks/useAddUser/index.ts
src/pages/users/addUser/roleSelector/index.tsx
src/pages/users/addUser/types.ts
src/pages/users/context/apiContextProvider.tsx
src/pages/users/listUsers/ListUsers.tsx
src/pages/users/listUsers/userRow/index.tsx

New feat: added (CheckList.tsx) and styling, update to (apiContextProvider) to fetch all checklists and checklistsbyUserID

--------------

---

src/App.tsx
src/components/navigation/Navigation.tsx
src/models/CategoryEntity.ts
src/models/FormValuesEntity.ts
src/pages/checklist/addchecklists/AddCheckList.tsx
src/pages/checklist/addchecklists/CategoryList.tsx
src/pages/checklist/addchecklists/InputCheckList.tsx
src/pages/checklist/addchecklists/TaskInput.tsx
src/pages/checklist/addchecklists/styles.ts
src/pages/checklist/addchecklists/useAddCheckList/Index.tsx
src/pages/checklist/allchecklists/CheckList.tsx
src/pages/checklist/allchecklists/CheckListRowAll.tsx
src/pages/checklist/allchecklists/styles.ts
src/pages/checklist/checkListID/CheckListIDrow.tsx
src/pages/checklist/checkListID/MyCheckListNav.tsx
src/pages/checklist/checkListID/MyCheckLists.tsx
src/pages/checklist/checkListID/styles.ts
src/pages/checklist/previewCheckList/Preview.tsx
src/pages/checklist/previewCheckList/hooks/usePreviewList/index.tsx
src/pages/checklist/styles.ts
src/pages/context/apiContextProvider.tsx
src/pages/users/addUser/AddUser.tsx
src/pages/users/addUser/addUserNavigation/AddUserNAV.tsx

feat(App.tsx): add new routes for AddCheckList and AddCheckList/:id to support adding and editing checklists
feat(Navigation.tsx): add condition to hide footer in certain routes
feat(CategoryEntity.ts): add new model for Category
feat(FormValuesEntity.ts): add new model for FormValues
feat(AddCheckList.tsx): create new component for adding checklists
feat(AddCheckListNav.tsx): create new component for navigation in AddCheckList
feat(CategoryList.tsx): create new component for selecting category in AddCheckList
feat(InputCheckList.tsx): create new component for input fields in AddCheckList
feat(TaskInput.tsx): create new component for adding tasks in AddCheckList
feat(styles.ts): add styles for AddCheckList components
feat(checklist): add useAddCheckList hook to handle form submission and …

---add checklist and checklist component plus other feats listed below

---

src/pages/users/addUser/roleSelector/index.tsx

fix:update user without needing to change userRole

---

package.json

Updating version number
New features has been implemented
Updated version number in package.json

chore: updated version number

---

src/App.tsx
src/components/RoutesContainer.tsx
src/components/addtasks/AddTasks.tsx
src/components/addtasks/useAddTaskForm/index.tsx
src/pages/checklist/allchecklists/CheckList.tsx
src/pages/checklist/allchecklists/CheckListRowAll.tsx
src/pages/checklist/allchecklists/receivedCheckLists.tsx
src/pages/checklist/checkListID/CheckListIDrow.tsx
src/pages/checklist/checkListID/MyCheckLists.tsx
src/pages/checklist/editchecklist/context/editCheckListContextProvider.tsx
src/pages/checklist/editchecklist/editCheckList.tsx
src/pages/checklist/workflow/context/workFlowContextProvider.tsx
src/pages/context/CheckListContextProvider.tsx

using workflow context to fetch out info regarding checklists, inspectors can see the checklists assigned to them and leaders can see the checklists they have send to inspectors(checklists in the workflow endpoint). Code needs clean up.

(feat)/#94/inspector/checklistworkflowcontext

---

src/pages/punch/Punch.tsx
src/pages/punch/addPunch/AddPunch.tsx
src/pages/punch/addPunch/AddPunchHook.tsx
src/pages/punch/addPunch/styles.ts
src/pages/punch/context/PunchContextProvider.tsx
src/pages/punch/listPunches/index.tsx
src/pages/punch/severityButton/SeverityButton.tsx
src/pages/punch/types.ts

Improved/fixed punch functionality after adding the functionality to add punch by task.

Fixing punch after checklist punch merge

---

src/Helpers/index.ts
src/components/RoutesContainer.tsx
src/components/header/Header.tsx
src/components/navigation/hooks/DefaultNavigation.tsx
src/pages/checklist/LeaderTabs.tsx
src/pages/checklist/allchecklists/InspectorCheckList.tsx
src/pages/checklist/index.tsx
src/pages/punch/Index.tsx
src/pages/punch/addPunch/AddPunch.tsx
src/pages/punch/addPunch/styles.ts
src/pages/punch/listPunches/index.tsx
src/pages/punch/listPunches/styles.ts
src/pages/punch/severityButton/SeverityButton.tsx
src/pages/punch/styles.ts

fixed #123 
- changed titles (CheckList is now Checklist)

Punch fixes and header title changes

---

src/components/sidebar/Sidebar.tsx

fixed #225 
- added navigate('/') before making the logout call

fix: navigate to "/" on sign out

---

src/pages/punch/addPunch/AddPunchHook.tsx
src/services/api.ts
src/services/apiTypes.ts

fixed #227
- using api service for endpoints
- update punch as inspector fixed

fix: bug fix + using api service for endpoints

---

src/main.tsx
src/pages/punch/severityButton/SeverityButton.tsx
src/style/App.css
src/style/GlobalStyles.ts

fixed #234 
- adding global styles

feat: adding global styles for styled components

---

src/pages/profile/index.tsx
src/pages/profile/styles.ts
src/pages/users/addUser/styles.ts
src/pages/users/hooks/useAddUser.ts
src/pages/users/listUsers/ListUsers.tsx
src/pages/users/listUsers/styles.ts
src/pages/users/listUsers/userRow/index.tsx

Refactor/#239/profile + user page colors

---

src/pages/punch/styles.ts

fixed #236 
- span style set wrong color on button text..
- Removed unused code

fix: button text color + removed comments

---

src/pages/punch/addPunch/AddPunch.tsx
src/pages/punch/addPunch/styles.ts

refactor: replacing inlinestyle w/styled components

---

src/pages/punch/listPunches/index.tsx
src/pages/punch/listPunches/styles.ts

refactor: display punch list in a table

---

src/pages/punch/listPunches/index.tsx

fixed #276 
- redundant dialog box removed

refactor: remove dialog box

---

src/pages/punch/addPunch/AddPunch.tsx
src/pages/punch/styles.ts

fix: punch image size

---

index.html

feat: website title
